#!/bin/bash -e
( git checkout $(whoami) || git checkout -b $(whoami) ) 2>/dev/null

current_exercise_no=$(ls *.go | grep -oE "^[0-9]{2}.*_test.go" | grep -oE "^[0-9]{2}" | sort | tail -n 1)

git fetch --all

if ! git branch -a | grep "/origin/${current_exercise_no}-solution$" &> /dev/null
then
  echo "die Lösung ist noch nicht verfügbar"
  exit 1
fi

git merge --no-ff -m "Fetching solution for exercise ${current_exercise_no}" origin/${current_exercise_no}-solution

echo "Lösung wurde heruntergeladen ... jetzt noch mal ./next ausführen"
