#!/bin/bash -e

current_exercise_no=$(ls *.go | grep -oE "^[0-9]{2}.*_test.go" | grep -oE "^[0-9]{2}" | sort | tail -n 1|sed 's/^0//g')
next_exercise_no="$(printf "%d" "$(( ${current_exercise_no} + 1))")"

(git checkout $(whoami) || git checkout -b $(whoami) ) 2>/dev/null

go test -v .

badly_formatted_files="$(gofmt -e -l .)"
if [ "${badly_formatted_files}" != "" ]
then
  echo "Folgende Dateien sind nicht korrekt formatiert: ${badly_formatted_files}"
  exit 2
fi

if ! git status | grep "nothin.*to commit" &> /dev/null
then
  git add *.go && git commit --allow-empty -anm "Commit exercise $(printf "%02d" ${current_exercise_no})"
fi

git fetch --all

if ! git branch -a | grep "/origin/${next_exercise_no}$" &> /dev/null
then
  echo "die nächste Übung ist noch nicht verfügbar"
  exit 1
fi

git merge --no-ff -m "Fetching exercise ${next_exercise_no}" origin/${next_exercise_no}

cat ${next_exercise_no}_instructions.txt
